channels:
  - conda-forge
  - nodefaults
dependencies:
  - cython                # and any other build deps
  - numpy
  - python >=3.8,<3.9    # or whatever version
  - jupyterlab >=3.4.4,<4 # or whatever version
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu102
    - Cython
    - hyperopt==0.2.5
    - tensorflow
    - tqdm
    - scipy
    - pandas
    - Pillow
    - PyYAML
    - scikit_learn
    - gdown
    - torch==1.13.0+cu116
    - -f https://data.pyg.org/whl/torch-1.12.0+cu102.html
    - sparsesvd==0.2.0
    - torch_geometric
    - torch-scatter
    - torch_sparse
    - torch_cluster
    - torch_spline_conv
