experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    test_path: ../data/{0}/train.tsv
    train_path: ../data/{0}/test.tsv
  dataset: yelp-2018
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SVDGCN:
      meta:
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      factors: 64
      epochs: 15
      batch_size: 256
      l_w: 0.01
      lr: 9
      req_vec: 60
      beta: 2
      alpha: 3
      coef_u: 0.5
      coef_i: 0.7
      seed: 123
