experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/validation.tsv
    test_path: ../data/{0}/test.tsv
  dataset: bookcrossing
  top_k: 20
  evaluation:
    cutoffs: [20]
    simple_metrics: [Recall, nDCG]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.UltraGCN:
      meta:
        verbose: True
        save_weights: True
        validation_rate: 10
        validation_metric: Recall@20
        restore: False
        write_best_iterations: True
      lr: 1e-4
      epochs: 2000
      factors: 64
      batch_size: 128
      g: 1e-4
      l: 2.1590977284940767
      w1: 0.4071845141372458
      w2: 2.674735729193082e-06
      w3: 0.11655266791027195
      w4: 0.05001575677944944
      ii_n_n: 10
      n_n: 300
      n_w: 300
      s_s_p: False
      i_w: 1e-4
      seed: 42
      early_stopping:
        patience: 15
        mode: auto
        monitor: Recall@20
        verbose: True
